name: Auto Run Python Every Morning

on:
  schedule:
    - cron: "0 1 * * *"  # รันทุกวันเวลา 8 โมงเช้า (1:00 UTC)
  workflow_dispatch:      # เผื่ออยากกดรันเองด้วย

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run your Python script
        run: python main.py
